### PR TITLE
fix: use clamp to ignore line sizes when --lines is 0 for rect

### PR DESCRIPTION
**Pull request by themagickoala**
Hi there, I'm using this library in an enterprise project and will hopefully be making further issues/pull requests with any tweaks I think are helpful in the future. Please let me know if you have any contribution guidelines you'd like me to follow. Happy to chat about it further if you'd like!

This change uses the clamp function to only take the line height, line gap and group gap into account if lines is > 0. That way you can have pure block skeletons.

### CODE REVIEW

**Comment by dgknca** [comment]
Hi 👋 I'm happy to get my first PR! Thank you so much. But I didn't understand exactly what you want to do. What was the issue, maybe I can suggest you another way. Can you create a jsfiddle demo I can peek at?

I don't have a contribution guideline for now. Feel free to submit pull requests or create issues, I'd be happy!

I'll also try to add comments to make the code clearer when I have time.

**Comment by themagickoala** [comment]
Sure, here's a codepen that demonstrates what the change does: https://codepen.io/themagickoala/pen/JjELmZK.

You can see that there's a 5px gap beneath the rect in the current version, but the new version has no such gap, while maintaining consistent behaviour when you don't have lines set to 0.

This 5px is the difference between `--l-gap` and `--g-gap`, as you're getting -1 of the former and 1 of the latter.

**Comment by dgknca** [comment]
ok get it thanks! released v1.0.5

**Comment by themagickoala** [comment]
Thanks! A member of my team has put together a React component system based on your library which we're keen to open source at some point. It's not ready for release yet, but we'll look into doing so soon!

I'll take a look at some ways to tidy up the repo in terms of making contribution easier. How do you tend to make your changes? Do you update the SCSS and use that to build the .css and .min.css files?

**Comment by dgknca** [comment]
It would be great! Unfortunately I was wrote this repo very complicated. Just update the .scss file and run `gulp` command. If you need any help feel free to write to me.

**Pull request merged**
